version: "3"
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
    ports:
      - "8000:8000"
    environment:
      DEV_SERVER: 1
      APPLY_MIGRATIONS: 1
      ALLOWED_HOSTS: "*"
      ADMIN_USER_PASSWORD: "admin"
  frontend:
    build: ./frontend
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      VITE_API_ENDPOINT: http://localhost:8000/tester
volumes:
  static_volume:
