# Generated by Django 3.2.8 on 2021-10-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(help_text='When this answer to coding assignment was tested as working')),
                ('assignment_name', models.CharField(default='', help_text='The name of the coding assignment this is a submission for', max_length=256)),
                ('submission_endpoint_address', models.URLField(help_text='The address (endpoint) where this answer was tested', max_length=2048)),
                ('applicant_name', models.CharField(default='', help_text="Applicant's name", max_length=256)),
                ('applicant_phone', models.CharField(default='', help_text="Applicant's phone number", max_length=15)),
                ('applicant_address', models.EmailField(help_text="Applicant's contact email address", max_length=2048)),
                ('submission_code_address', models.URLField(help_text='Address where the code implementing the submission can be found', max_length=2048)),
                ('own_tech_competence', models.TextField(help_text="Applicant's tech competence", max_length=2048)),
                ('work_experience', models.TextField(help_text="Applicant's work experience", max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='PassedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.TextField()),
                ('test_output', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.submission')),
            ],
        ),
    ]
